name: "Riden RD60xx MQTT Bridge HA Add-on"
version: "1.0.2"
slug: "riden_rd60xx_ha_addon"
description: "Accepts Riden W0x TCP (8080) connections and publishes controls/status to MQTT"
url: "https://github.com/DetFisch/Riden-RD60xx-MQTT-Bridge-Home-Assistant-Addon"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
init: false
services:
  - mqtt:need
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Riden PSU bridge (TCP)"
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_prefix: "riden"
  mqtt_discovery_enabled: true
  mqtt_discovery_prefix: "homeassistant"
  default_update_period: 5
  psu_addresses: "1"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str?
  mqtt_password: password?
  mqtt_prefix: str
  mqtt_discovery_enabled: bool?
  mqtt_discovery_prefix: str?
  default_update_period: float?
  psu_addresses: str?
